sudo: required

services:
  - docker

before_install:
  - docker build -t linagora/esn-mongo .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push linagora/esn-mongo

script:
  - docker ps

notifications:
  email:
    - lgs-openpaas-dev@linagora.com
